#!/usr/bin/env bash

##
# Cats the command's usage documentation.
##
__app_command::usage() {
    cat << EOF

$APP_NAME ($APP_VERSION)

Navigate the murky waters of git submodules...

Usage:  $APP_NAME [option]
        $APP_NAME <command> [args]

Options:
    -h, --help      Print usage information

Commands:
    install     Installs a project's configured submodules.
    list        TODO: list all of a project's configured submodules.
    remove      Remove submodules from a project
    require     Add required submodules to a project
    status      TODO: print the status of a project's configured submodules.
    uninstall   Uninstall a project's installed submodules
    update      Update a project's installed submodules to the latest version of
                the required branch

EOF
}

##
# Handles incoming command requests.
##
__app_command::handle() {
    local opt="$1"
    local args=${@:2}

    case "$opt" in
        install)
            source "$command/install-command" "${args[@]}"
        ;;
        remove)
            source "$command/remove-command" "${args[@]}"
        ;;
        require)
            source "$command/require-command" "${args[@]}"
        ;;
        uninstall)
            source "$command/uninstall-command" "${args[@]}"
        ;;
        update)
            source "$command/update-command" "${args[@]}"
        ;;
        *)
            __app_command::usage
            return 0
        ;;
    esac
}

__app_command::handle $@
