#!/usr/bin/env bash

source "$feature/install-feature"

##
# Cats the command's usage documentation.
##
__install_command::usage() {
    cat << EOF
$APP_NAME ($APP_VERSION) - Install

Installs a project's configured submodules.

Usage:  $APP_NAME install [<options>] | [<name|path>...]

Options:
    -a, --all       Install all submodules
    -h, --help      Print usage information

EOF
}

##
# Handles incoming command requests.
##
__install_command::handle() {
    local submodules=()

    while [[ "$#" -gt 0 ]]; do
        case $1 in
            -a|--all)
                install_feature::install_all && return 0
            ;;
            -h|-*|--help|--*)
                __install_command::usage && return 0
            ;;
            *)
                submodules+=("$1")
            ;;
        esac

        shift
    done

    install_feature::install_named ${submodules[@]}
}

# handle empty args
[[ -z "$@" ]] && set -- "--help"

__install_command::handle $@
