#!/usr/bin/env bash

source "$FEATURE/install-feature"

##
# Cats the command's usage documentation.
##
__install_command::usage() {
    cat << EOF
$APP_NAME ($APP_VERSION) - Install

Installs a project's configured submodules.

Usage:  $APP_NAME install [<options>] | [<name|path>...]

Options:
    -a, --all       Install all submodules
    -n, --no-dev    Skip installation of dev dependencies with the --all option
    -h, --help      Print usage information

EOF
}

##
# Handles incoming command requests.
##
__install_command::handle() {
    local all=false
    local dev=true
    local submodules=()

    while [[ "$#" -gt 0 ]]; do
        case $1 in
            -n|--no-dev)
                dev=false ;;
            -a|--all)
                all=true ;;
            -h|-*|--help|--*)
                __install_command::usage && return 0
            ;;
            *)
                submodules+=("$1")
            ;;
        esac

        shift
    done

    if "$all"; then
        install_feature::install_all $dev
    else
        install_feature::install_named ${submodules[@]}
    fi
}

# handle empty args
[[ -z "$@" ]] && set -- "--help"

__install_command::handle $@
