#!/usr/bin/env bash

source "$feature/remove-feature"

##
# Cats the command's usage documentation.
##
__remove_command::usage() {
    cat << EOF

$APP_NAME ($APP_VERSION)

Remove submodules from a project.

Usage:  $APP_NAME remove [<options>] | [<name>...]

Options:
    -a, --all       Remove all submodules
    -h, --help      Print usage information

EOF
}

##
# Handles incoming remove commands.
##
__remove_command::handle() {
    local names=()

    while [[ "$#" -gt 0 ]]; do
        case $1 in
            -a|--all)
                remove_feature::remove_all && return 0
            ;;
            -h|-*|--help|--*)
                __remove_command::usage && return 0
            ;;
            *)
                names+=("$1")
            ;;
        esac

        shift
    done

    remove_feature::remove_named ${names[@]}
}

# handle empty args
[[ -z "$@" ]] && set -- "--help"

__remove_command::handle $@
