#!/usr/bin/env bash

source "$FEATURE/require-feature"

##
# Cats the command's usage documentation.
##
__require_command::usage() {
    cat << EOF

$APP_NAME ($APP_VERSION) - Require

Add required submodules to a project.

Usage:  $APP_NAME require [<options>] [--] <repo> [<name>]

Options:
    -b, --branch    The required branch (default: master)
    -f, --force     Allows adding an otherwise ignored submodule path
    -h, --help      Print usage information

EOF
}

##
# Handles incoming command requests.
##
__require_command::handle() {
    local args=()
    local branch="master"
    local force=false
    # TODO: add local depth=1 here and to update commands too
    local positionals=()

    while [[ "$#" -gt 0 ]]; do
        case $1 in
            -b|--branch)
                branch="$2" && shift
            ;;
            -f|--force)
                force=true
            ;;
            -h|-*|--help|--*)
                __require_command::usage && return 0
            ;;
            *)
                positionals+=("$1")
            ;;
        esac

        shift
    done

    if [[ ${#positionals[@]} -eq 0 ]]; then
        __require_command::usage && return 0
    fi

    local name="${positionals[1]:-$(
        require_feature::parse_name_from_repo "${positionals[0]}"
    )}"
    positionals[1]="$SUBMODULES_DIR/$name"

    local options=(
        --branch "$branch"
        $($force && echo "--force")
        --name "$name"
    )

    require_feature::require "${options[@]}" -- "${positionals[@]}"
}

# handle empty args
[[ -z "$@" ]] && set -- "--help"

__require_command::handle $@
