#!/usr/bin/env bash

source "$FEATURE/uninstall-feature"

##
# Cats the command's usage documentation.
##
__uninstall_command::usage() {
    cat << EOF
$APP_NAME ($APP_VERSION) - uninstall

Uninstall a project's installed submodules.

Usage:  $APP_NAME uninstall [<options>] | [<name|path>...]

Options:
    -a, --all       Uninstall all submodules
    -h, --help      Print usage information

EOF
}

##
# Handles incoming command requests.
##
__uninstall_command::handle() {
    local submodules=()

    while [[ "$#" -gt 0 ]]; do
        case $1 in
            -a|--all)
                uninstall_feature::uninstall_all && return 0
            ;;
            -h|-*|--help|--*)
                __uninstall_command::usage && return 0
            ;;
            *)
                submodules+=("$1")
            ;;
        esac

        shift
    done

    uninstall_feature::uninstall_named ${submodules[@]}
}

# handle empty args
[[ -z "$@" ]] && set -- "--help"

__uninstall_command::handle $@
