#!/usr/bin/env bash -f
# -f is used to disable variable expansion, allowing use of '*' as a version
# constraint

APP_VERSION="$(cat $__app_dir/version)"

source "$__app_dir/.env"

APP_NAME="${APP_NAME:-$(basename $0)}"
SUBMODULES_DIR="${SUBMODULES_DIR:-submodules}"

AUTOLOAD_RESOURCE="$__app_dir/resource/autoload"

__app_src="$__app_dir/src"

source "$__app_src/kernel" $@
