#!/usr/bin/env bash -f
# -f is used to disable variable expansion, allowing use of '*' as a version
# constraint

__script=$(readlink "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")
__app_dir="$(cd $(dirname "$__script"); pwd)"

APP_VERSION="$(cd $__app_dir; git describe --always --first-parent HEAD 2>/dev/null)"

source "$__app_dir/.env"

APP_NAME="${APP_NAME:-$(basename $0)}"
SUBMODULES_DIR="${SUBMODULES_DIR:-submodules}"

AUTOLOAD_RESOURCE="$__app_dir/resource/autoload"

__app_src="$__app_dir/src"

source "$__app_src/kernel" $@
