#!/usr/bin/env bash

__app_dir=$(dirname $(perl -e "use Cwd 'abs_path'; print abs_path(@ARGV[0])" -- "$0"))

APP_VERSION="$(cd $__app_dir; git describe --always --first-parent HEAD 2>/dev/null)"

source "$__app_dir/.env"

APP_NAME="${APP_NAME:-$(basename $0)}"
SUBMODULES_DIR="${SUBMODULES_DIR:-submodules}"

AUTOLOAD_RESOURCE="$__app_dir/resource/autoload"

__app_src="$__app_dir/src"

source "$__app_src/kernel" $@
