#!/usr/bin/env bash

__script_dir="$(dirname "${BASH_SOURCE[0]}")"
source "$__script_dir/../../../../bootstrap"

__strategy="$__src_dir/service/version/constraint/strategy/hyphenated-strategy"
__version_examiner="$__src_dir/service/version/version-examiner"

hyphenated_strategy_test::test_explicit_hyphenated_range() {
    local actual

    source "$__strategy" "1.0.0 - 2.0.0" "$__version_examiner"

    actual=$(constraint_strategy::is_satisfied_by "0.0.1"; echo $?)
    bash_test::assert_equals 1 $actual

    actual=$(constraint_strategy::is_satisfied_by "0.9.9"; echo $?)
    bash_test::assert_equals 1 $actual

    actual=$(constraint_strategy::is_satisfied_by "1.0.0"; echo $?)
    bash_test::assert_equals 0 $actual

    actual=$(constraint_strategy::is_satisfied_by "1.5.0"; echo $?)
    bash_test::assert_equals 0 $actual

    actual=$(constraint_strategy::is_satisfied_by "2.0.0"; echo $?)
    bash_test::assert_equals 0 $actual

    actual=$(constraint_strategy::is_satisfied_by "2.0.1"; echo $?)
    bash_test::assert_equals 1 $actual

    actual=$(constraint_strategy::is_satisfied_by "3.0.0"; echo $?)
    bash_test::assert_equals 1 $actual
}

hyphenated_strategy_test::test_truncated_hyphenated_range() {
    local actual

    # truncated values are handled as if they each had a wildcard added e.g.:
    #   "1.0.* - 2.0.*"
    source "$__strategy" "1.0 - 2.0" "$__version_examiner"

    actual=$(constraint_strategy::is_satisfied_by "0.1"; echo $?)
    bash_test::assert_equals 1 $actual

    actual=$(constraint_strategy::is_satisfied_by "0.0.1"; echo $?)
    bash_test::assert_equals 1 $actual

    actual=$(constraint_strategy::is_satisfied_by "0.1.0"; echo $?)
    bash_test::assert_equals 1 $actual

    actual=$(constraint_strategy::is_satisfied_by "1.0.0"; echo $?)
    bash_test::assert_equals 0 $actual

    actual=$(constraint_strategy::is_satisfied_by "1.0"; echo $?)
    bash_test::assert_equals 0 $actual

    actual=$(constraint_strategy::is_satisfied_by "1.5"; echo $?)
    bash_test::assert_equals 0 $actual

    actual=$(constraint_strategy::is_satisfied_by "1.5.0"; echo $?)
    bash_test::assert_equals 0 $actual

    actual=$(constraint_strategy::is_satisfied_by "2.0"; echo $?)
    bash_test::assert_equals 0 $actual

    actual=$(constraint_strategy::is_satisfied_by "2.0.0"; echo $?)
    bash_test::assert_equals 0 $actual

    actual=$(constraint_strategy::is_satisfied_by "2.0.1"; echo $?)
    bash_test::assert_equals 0 $actual

    actual=$(constraint_strategy::is_satisfied_by "2.1"; echo $?)
    bash_test::assert_equals 1 $actual

    actual=$(constraint_strategy::is_satisfied_by "2.1.0"; echo $?)
    bash_test::assert_equals 1 $actual
}

hyphenated_strategy_test::test_wildcard_hyphenated_range() {
    local actual="$(
        source "$__strategy" "1.* - 2.*" "$__version_examiner" 2>&1
    )"
    local expected="The hyphenated constraint '1.* - 2.*' cannot contain wildcards!"

    bash_test::assert_equals "$expected" "$actual"
}
