#!/usr/bin/env bash

source "$SERVICE/config-service"
source "$SERVICE/submodule-service"

##
# Installs all configured submodules.
##
install_feature::install_all() {
    local paths=$(config_service::get_configured_paths)

    for path in ${paths[@]}; do
        __install_feature::install $path
    done
}

##
# Installs the given submodule paths or names.
##
install_feature::install_named() {
    local submodules=$@

    for submodule in ${submodules[@]}; do
        local path=$(config_service::find_path_for_value "$submodule")

        if [[ -z $path ]] ; then
            echo "The submodule '$submodule' does not exist!"

            echo "Configured submodule paths:"
            for path in $(config_service::get_configured_paths); do
                echo " - $path"
            done

            return 1
        fi

        __install_feature::install $path
    done
}

##
# Installs the given submodule.
##
__install_feature::install() {
    local path=${1:?"A submodule path is required"}

    echo "Installing '$path'..."

    submodule_service::install_path $path
}
