#!/usr/bin/env bash

source "$SERVICE/autoload-service"
source "$SERVICE/config-service"
source "$SERVICE/submodule-service"

##
# Installs all configured submodules, optionally excluding dev dependencies.
##
install_feature::install_all() {
    local dev="${1:-true}"
    local paths=$(config_service::get_configured_paths)

    for path in ${paths[@]}; do
        if ! "$dev" && $(config_service::is_dev_dependency "$path"); then
            continue # we'll skip this dev dependency
        fi

        __install_feature::install $path
    done
}

##
# Installs the given submodule paths or names.
##
install_feature::install_named() {
    local submodules=$@

    for submodule in ${submodules[@]}; do
        local path=$(config_service::find_path_for_value "$submodule")

        if [[ -z $path ]] ; then
            echo "The submodule '$submodule' does not exist!"

            echo "Configured submodule paths:"
            for path in $(config_service::get_configured_paths); do
                echo " - $path"
            done

            return 1
        fi

        __install_feature::install $path
    done
}

##
# Installs the given submodule.
##
__install_feature::install() {
    local path=${1:?"A submodule path is required"}

    echo "Installing '$path'..."

    submodule_service::install_path $path

    if [[ $? -eq 0 ]]; then
        autoload_service::refresh
    fi
}
