#!/usr/bin/env bash

source "$SERVICE/autoload-service"
source "$SERVICE/config-service"
source "$SERVICE/submodule-service"

##
# Removes all registered submodules.
##
remove_feature::remove_all() {
    for path in $(config_service::get_configured_paths); do
        submodule_service::remove_indiscriminately $path
    done
}

##
# Removes the given submodule paths or names and their dependencies.
##
remove_feature::remove_named() {
    local submodules=$@

    for submodule in ${submodules[@]}; do
        local path=$(config_service::find_path_for_value "$submodule")

        if [[ -z $path ]] ; then
            echo "The submodule '$submodule' is not installed!"

            echo "Configured submodule paths:"
            for path in $(config_service::get_configured_paths); do
                echo " - $path"
            done

            return 1
        fi

        submodule_service::remove $path
    done
}
