#!/usr/bin/env bash

source "$service/submodule-service"

##
# Removes all registered submodules.
##
remove_feature::remove_all() {
    for path in $(submodule_service::get_all_paths); do
        __remove_feature::remove $path
    done
}

##
# Removes the given submodules paths or names.
##
remove_feature::remove_named() {
    local for_removal=$@

    local given
    for given in ${for_removal[@]}; do
        local path=$(submodule_service::get_path_from_given "$given")

        if [[ -z $path ]] ; then
            echo "The submodule '$given' does not exist. Available:"

            for path in $(submodule_service::get_all_paths); do
                echo " - $path"
            done

            return 1
        fi

        __remove_feature::remove $path
    done
}

##
# Removes the given submodule path.
##
__remove_feature::remove() {
    local path=$1

    echo "remove submodule: $path"

    # remove code from submodule directory, ignoring any local modifications
    # git submodule deinit --force -- $path

    # remove vestigial directories
    # rm -rf submodules/mymodule (if empty, replicate in .git/modules/)
    # local vendor=$(echo $path | sed -E "s|^$MODULES_DIR/(.+)/*|\1|")

    local vendor="$(echo $path | cut -d '/' -f 2)"
    local candidates=()

    for item in $(find "$GIT_DIR/$MODULES_DIR" -type d); do
        local candidate=$(echo $item | sed -E "s|^$GIT_DIR/$MODULES_DIR/||")

        if [[ $candidate =~ ^$vendor ]]; then
            candidates+=("$candidate")
        fi
    done

    local oldIFS=$IFS
    IFS=$'\n' candidates=($(sort -r <<< "${candidates[*]}"))
    IFS=$oldIFS && unset oldIFS

    echo "Removing empty submodule vendor directories:"
    for candidate in ${candidates[@]}; do
        if [ -z "$(ls -A $GIT_DIR/$MODULES_DIR/$candidate)" ]; then
            echo " - removing empty $candidate"

            rm -d $GIT_DIR/$MODULES_DIR/$candidate
        else
            echo " - skipping non-empty $candidate"
        fi
    done

    # remove submodule config
    # git rm -f mymodule --- removes config
}
