#!/usr/bin/env bash

source "$SERVICE/autoload-service"
source "$SERVICE/submodule-service"

##
# Requires a new git repo as a submodule for a project.
##
require_feature::require() {
    submodule_service::add true "$@"
    autoload_service::refresh
}

##
# Parses a submodule name from the git ssh repo address - i.e.:
# - git@gitlab.com:vendor/project.git -> vendor/project
##
require_feature::parse_name_from_repo() {
    local name=${1:?"A repo value is required"}

    echo ${name/.git/} | cut -d ':' -f 2
}
