#!/usr/bin/env bash

source "$service/submodule-service"

##
# Uninstalls installed submodules.
##
uninstall_feature::uninstall() {
    local submodules=$@

    if [[ -z "$submodules" ]]; then
        submodules=$(submodule_service::get_installed_paths)
    fi

    for submodule in ${submodules[@]}; do
        local path=$(submodule_service::get_path_for_value "$submodule")

        if [[ -z $path ]] ; then
            echo "The submodule '$submodule' is not installed!"

            echo "Installed submodule paths:"
            for path in $(submodule_service::get_installed_paths); do
                echo " - $path"
            done

            return 1
        fi

        echo "Uninstalling $path..."

        submodule_service::force_remove_repo $path
    done
}
