#!/usr/bin/env bash

source "$SERVICE/config-service"
source "$SERVICE/submodule-service"

##
# Uninstalls all installed submodules.
##
uninstall_feature::uninstall_all() {
    for path in $(submodule_service::get_installed_paths); do
        __uninstall_feature::uninstall $path
    done
}

##
# Uninstalls installed submodule path or names.
##
uninstall_feature::uninstall_named() {
    local submodules=$@

    for submodule in ${submodules[@]}; do
        local path=$(config_service::find_path_for_value "$submodule")

        if [[ -z $path ]] ; then
            echo "The submodule '$submodule' is not installed!"

            echo "Installed submodule paths:"
            for path in $(submodule_service::get_installed_paths); do
                echo " - $path"
            done

            return 1
        fi

        __uninstall_feature::uninstall $path
    done
}

##
# Uninstalls the given submodule.
##
__uninstall_feature::uninstall() {
    local path=${1:?"A submodule path is required"}

    echo "Uninstalling $path..."

    submodule_service::uninstall_path $path
}
