#!/usr/bin/env bash

source "$service/submodule-service"

##
# Updates all installed submodules.
##
update_feature::update_all() {
    local paths=$(submodule_service::get_installed_paths)

    for path in ${paths[@]}; do
        __update_feature::update $path
    done

    __update_feature::install_dependencies ${paths[@]}
}

##
# Updates the given submodule paths or names.
##
update_feature::update_named() {
    local submodules=$@
    local paths=()

    for submodule in ${submodules[@]}; do
        local path=$(submodule_service::get_path_for_value "$submodule")

        if [[ -z $path ]] ; then
            echo "The submodule '$submodule' is not installed!"

            echo "Installed submodule paths:"
            for path in $(submodule_service::get_installed_paths); do
                echo " - $path"
            done

            return 1
        fi

        __update_feature::update $path

        paths+=("$path")
    done

    __update_feature::install_dependencies ${paths[@]}
}

##
# Updates the given submodule.
##
__update_feature::update() {
    local path=${1:?"A submodule path is required"}

    echo "Updating $path..."

    submodule_service::update_path $path
}

##
# Installs submodule dependencies for a given array of paths.
##
__update_feature::install_dependencies() {
    local paths=$@

    for path in ${paths[@]}; do
        echo "Installing dependencies for '$path'"

        source "$service/dependency-service" $path
        dependency_service::install_dependencies
    done
}
