#!/usr/bin/env bash

# try to get base git directory of the project being navigated
GIT_PATH=$(git rev-parse --show-toplevel 2>/dev/null)

if [[ -z "$GIT_PATH" ]]; then
    echo "You are not in a git repository!"

    return 1
fi

# cd to the top-level git dir in the main process
cd "$GIT_PATH"

COMMAND="$__app_src/command"
FEATURE="$__app_src/feature"
SERVICE="$__app_src/service"

source "$COMMAND/app-command" $@
